version: "2"
services:
    views:
        image: webapp-views
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./views:/views
            - /views/node_modules
        links:
            - backend
        networks:
            - webappnetwork
    backend:
        image: webapp-backend
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./
            - /node_modules
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
