const Constants = {
	SET_NAME: "SET_NAME",
	SET_EMAIL: "SET_EMAIL",
	SET_PASSWORD: "SET_PASSWORD",
	SET_VERIFY_PASSWORD: "SET_VERIFY_PASSWORD",
	CHANGE_NAME_COLOR: "CHANGE_NAME_COLOR",
	CHANGE_EMAIL_COLOR: "CHANGE_EMAIL_COLOR",
	CHANGE_PASS_COLOR: "CHANGE_PASS_COLOR",
	CHANGE_VPASS_COLOR: "CHANGE_VPASS_COLOR",
	ERASE_CREDENTIALS: "ERASE_CREDENTIALS"
}

export default Constants;
