const Constants = {
	SET_STORIES_COUNT: "SET_STORIES_COUNT",
	ADD_STORIES_COUNT: "ADD_STORIES_COUNT",
	DELETE_STORIES_COUNT: "DELETE_STORIES_COUNT",
	SET_STORIES: "SET_STORIES",
	ADD_STORY: "ADD_STORY",
	EDIT_STORY: "EDIT_STORY",
	DELETE_STORY: "DELETE_STORY",
	SET_EDIT_STATE: "SET_EDIT_STATE",
	UPDATE_EDIT_STATE: "UPDATE_EDIT_STATE",
	DATABASE_INCREMENT: "DATABASE_INCREMENT",
	ENVIRONMENT: "ENVIRONMENT"
}

export default Constants;
