const Constants = {
	SET_STORIES_COUNT: "SET_STORIES_COUNT",
	ADD_STORIES_COUNT: "ADD_STORIES_COUNT",
	DELETE_STORIES_COUNT: "DELETE_STORIES_COUNT",
	SET_STORIES: "SET_STORIES"
}

export default Constants;
